"""initial schema

Revision ID: 7660a019846c
Revises: 
Create Date: 2026-09-18 23:07:17.387072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7660a019846c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('checklists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklists_document_id'), ['document_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_checklists_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_user_id'), ['user_id'], unique=False)

    op.create_table('clauses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('section_ref', sa.String(length=100), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('plain_language_explanation', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('potential_implications', sa.Text(), nullable=False),
    sa.Column('questions_for_lawyer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clauses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clauses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_clauses_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clauses_id'), ['id'], unique=False)

    op.create_table('document_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('parties', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.String(length=100), nullable=True),
    sa.Column('governing_jurisdiction', sa.String(length=150), nullable=True),
    sa.Column('key_terms', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_analysis_document_id'), ['document_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_document_analysis_id'), ['id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_id'), ['id'], unique=False)

    op.create_table('document_comparisons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('doc_a_id', sa.String(length=36), nullable=False),
    sa.Column('doc_b_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('diff_data', sa.Text(), nullable=False),
    sa.Column('key_takeaways', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doc_a_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doc_b_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_comparisons_doc_a_id'), ['doc_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comparisons_doc_b_id'), ['doc_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comparisons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comparisons_user_id'), ['user_id'], unique=False)

    op.create_table('important_dates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('date_str', sa.String(length=100), nullable=False),
    sa.Column('date_type', sa.String(length=100), nullable=False),
    sa.Column('section_ref', sa.String(length=100), nullable=False),
    sa.Column('action_required', sa.Text(), nullable=True),
    sa.Column('consequence_if_missed', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('important_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_important_dates_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_important_dates_id'), ['id'], unique=False)

    op.create_table('obligations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('party_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('deadline_info', sa.String(length=255), nullable=True),
    sa.Column('consequence_of_breach', sa.Text(), nullable=True),
    sa.Column('section_ref', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obligations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obligations_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligations_party_type'), ['party_type'], unique=False)

    op.create_table('risks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('section_ref', sa.String(length=100), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('mitigation_suggestion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_level'), ['level'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('related_clauses', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checklist_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('section_ref', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_checklist_id'), ['checklist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_items_id'), ['id'], unique=False)

    op.create_table('document_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('vector_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_embeddings_chunk_id'), ['chunk_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_document_embeddings_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_embeddings_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_embeddings_id'))
        batch_op.drop_index(batch_op.f('ix_document_embeddings_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_embeddings_chunk_id'))

    op.drop_table('document_embeddings')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_items_checklist_id'))

    op.drop_table('checklist_items')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risks_level'))
        batch_op.drop_index(batch_op.f('ix_risks_id'))
        batch_op.drop_index(batch_op.f('ix_risks_document_id'))

    op.drop_table('risks')
    with op.batch_alter_table('obligations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obligations_party_type'))
        batch_op.drop_index(batch_op.f('ix_obligations_id'))
        batch_op.drop_index(batch_op.f('ix_obligations_document_id'))

    op.drop_table('obligations')
    with op.batch_alter_table('important_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_important_dates_id'))
        batch_op.drop_index(batch_op.f('ix_important_dates_document_id'))

    op.drop_table('important_dates')
    with op.batch_alter_table('document_comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_comparisons_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_comparisons_id'))
        batch_op.drop_index(batch_op.f('ix_document_comparisons_doc_b_id'))
        batch_op.drop_index(batch_op.f('ix_document_comparisons_doc_a_id'))

    op.drop_table('document_comparisons')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('document_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_document_analysis_document_id'))

    op.drop_table('document_analysis')
    with op.batch_alter_table('clauses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clauses_id'))
        batch_op.drop_index(batch_op.f('ix_clauses_document_id'))
        batch_op.drop_index(batch_op.f('ix_clauses_category'))

    op.drop_table('clauses')
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklists_user_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_document_id'))

    op.drop_table('checklists')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_document_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))

    op.drop_table('documents')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
